"""
==========================================================
This module contains utility functions for the IDC ABM simulation
built on the Covasim framework.

Author: Liping Peng
Institution: The University of Hong Kong
Date: 22 September 2026
"""

import pandas as pd
import numpy as np
import os
import networkx as nx


def func_create_folder(path, folder_name):
    """
    Create a directory for storing simulation results if it doesn't exist.

    Args:
        path (str): Base path where the folder should be created
        folder_name (str): Name of the subfolder to create
    """
    folder_name = path + "/" + folder_name
    folder = os.path.exists(folder_name)
    if not folder:
        os.makedirs(folder_name)


def fun_tree_indi_R(df):
    """
    Calculate the individual reproduction number (number of secondary cases per infector)
    and compute cumulative proportions to analyze transmission dispersion (e.g., superspreading/20-80 rule).

    Args:
        df (pd.DataFrame): A DataFrame containing transmission log details.
                           Must include 'source' and 'target' columns.

    Returns:
        pd.DataFrame: A sorted DataFrame containing:
            - source: UID of the infector.
            - reproduction_number: Number of secondary cases caused by the source.
            - cumulative_proportion_infectious: Cumulative fraction of infectors (sorted descending by R).
            - cumulative_proportion_transmissions: Cumulative fraction of total transmissions they caused.
    """

    # Calculate the number of secondary infections (individual R) for each source
    individual_r = df.groupby("source")["target"].count().reset_index()
    individual_r.columns = ["source", "reproduction_number"]

    # Filter out individuals with zero secondary cases and sort descending by reproduction number
    # Note: Unlike network degree calculations (e.g., G.out_degree), this dataframe-based approach
    # intrinsically excludes initial seed infections (e.g., pop_infected) if they did not transmit the disease.
    individual_r = individual_r[individual_r["reproduction_number"] > 0].sort_values("reproduction_number",ascending=False)

    # Calculate the cumulative proportion of infectors (X-axis for Lorenz curve / dispersion analysis)
    individual_r["cumulative_proportion_infectious"] = np.arange(1, len(individual_r) + 1) / len(individual_r)

    # Calculate the cumulative proportion of total transmissions (Y-axis for Lorenz curve / dispersion analysis)
    total_transmissions = individual_r["reproduction_number"].sum()
    individual_r["cumulative_transmissions"] = individual_r["reproduction_number"].cumsum()
    individual_r["cumulative_proportion_transmissions"] = (individual_r["cumulative_transmissions"] / total_transmissions)

    return individual_r




def age_group(age):
    """
    Categorize continuous age values into predefined discrete age bins for stratification.
    """
    if age < 12:
        return '<12'
    elif 12 <= age < 18:
        return '12-18'
    elif 18 <= age < 25:
        return '18-25'
    elif 25 <= age < 45:
        return '25-45'
    elif 45 <= age < 65:
        return '45-65'
    else:
        return '>=65'


def func_cal_infection(sim, df):
    """
    Compile temporal and age-stratified infection statistics from the simulation.

    Args:
        sim (cv.Sim): The executed Covasim simulation object.
        df (pd.DataFrame): The transmission log generated by the simulation.

    Returns:
        list: Contains the merged daily infection statistics [0] and
              a 10x10 age-group transmission matrix [1].
    """
    all_times = pd.DataFrame({'date': range(0, sim.t + 1)})

    # 1. Total infected population per timestep
    total_infected = df.groupby('date')['target'].nunique().reset_index()
    total_infected_per_time = all_times.merge(total_infected, on='date', how='left').fillna(0)
    total_infected_per_time.columns = ['date', 'total_infected_count']

    # 2. Infected individuals grouped by age_target per timestep
    df['age_group_target'] = df['age_target'].apply(age_group)
    infected_by_age_target = (df.groupby(['date', 'age_group_target'])['target'].nunique().unstack(fill_value=0))

    all_age_groups = ['<12', '12-18', '18-25', '25-45', '45-65', '>=65']
    infected_by_age_target = infected_by_age_target.reindex(columns=all_age_groups, fill_value=0)
    infected_by_age_target = all_times.merge(infected_by_age_target.reset_index(), on='date', how='left').fillna(0)

    # 3. Transmissions grouped by age_source per timestep
    df['age_group_source'] = df['age_source'].apply(age_group)
    transmissions_by_age_source = (df.groupby(['date', 'age_group_source'])['target'].count().unstack(fill_value=0))

    transmissions_by_age_source = transmissions_by_age_source.reindex(columns=all_age_groups, fill_value=0)
    transmissions_by_age_source = all_times.merge(transmissions_by_age_source.reset_index(), on='date',
                                                  how='left').fillna(0)

    final_age_stats = pd.merge(infected_by_age_target, transmissions_by_age_source,
                               on='date', suffixes=('_infected', '_transmitted'))

    # 4. Transmissions segmented by contact layer per timestep
    layer_transmission = df.groupby(['date', 'layer']).size().unstack(fill_value=0)
    layer_transmission = layer_transmission.reindex(pd.Index(all_times['date']), fill_value=0)

    all_daily_infection = pd.concat([total_infected_per_time, final_age_stats, layer_transmission], axis=1)
    all_daily_infection = all_daily_infection.loc[:, ~all_daily_infection.columns.duplicated()]

    # 5. Formulate 10-year bin transmission matrix
    bins = list(range(0, 101, 10)) + [np.inf]
    labels = [f"{i}-{i + 9}" for i in range(0, 100, 10)] + ["100+"]

    df['age_group_source_10'] = pd.cut(df['age_source'], bins=bins, labels=labels, right=False)
    df['age_group_target_10'] = pd.cut(df['age_target'], bins=bins, labels=labels, right=False)

    transmission_matrix_10x10 = (
        df.groupby(['age_group_source_10', 'age_group_target_10']).size().unstack(fill_value=0))
    all_age_10_groups = labels
    transmission_matrix_10x10 = transmission_matrix_10x10.reindex(
        index=all_age_10_groups,
        columns=all_age_10_groups,
        fill_value=0)

    return [all_daily_infection, transmission_matrix_10x10]


def calculate_attack_rate(sim, df):
    """
    Calculate the overall and age-stratified attack rates (cumulative incidence)
    for the simulated population.

    Args:
        sim (cv.Sim): The executed Covasim simulation object.
        df (pd.DataFrame): The transmission log.

    Returns:
        pd.DataFrame: A summary table detailing population counts, infection counts,
                      and calculated attack rates per age group and overall.
    """

    total_population = len(sim.people)
    all_infected_ids = df['target'].unique()
    total_infected = len(all_infected_ids)

    age_series = pd.Series(sim.people.age)
    age_groups = age_series.apply(age_group)

    pop_df = pd.DataFrame({
        'uid': range(total_population),
        'age': sim.people.age,
        'age_group': age_groups
    })

    pop_df['infected'] = pop_df['uid'].isin(all_infected_ids).astype(int)

    age_group_summary = pop_df.groupby('age_group').agg(
        population=('uid', 'count'),
        infected=('infected', 'sum')
    )
    age_group_summary['attack_rate'] = age_group_summary['infected'] / age_group_summary['population']

    overall_row = pd.DataFrame({
        'age_group': ['overall'],
        'population': [total_population],
        'infected': [total_infected],
        'attack_rate': [total_infected / total_population]
    })

    age_group_summary = age_group_summary.reset_index()
    final_summary = pd.concat([age_group_summary, overall_row], ignore_index=True)

    return final_summary



def func_combine_data(sim=None, output_path=None, n=None):
    """
    Aggregate, process, and export comprehensive simulation outputs, including
    network cluster sizes, generation intervals, and effective reproduction numbers.

    Args:
        sim (cv.Sim): Executed simulation object.
        output_path (str): Destination directory for the exported Excel file.
        n (int): Simulation seed/index for file naming.
    """
    df = pd.DataFrame(sim.people.infection_log)

    # Reconstruct Directed Graph for cluster analysis
    df_clean = df.dropna(subset=['source'])
    G = nx.from_pandas_edgelist(
        df_clean,
        source='source',
        target='target',
        edge_attr='date',
        create_using=nx.DiGraph()
    )

    infected_targets = set(df['target'])
    infected_sources = set(df['source'].dropna())
    all_infected = infected_targets.union(infected_sources)
    G.add_nodes_from(all_infected)

    # 1. Cluster size distribution
    clusters = list(nx.weakly_connected_components(G))
    cluster_sizes = [len(c) for c in clusters]
    output_cluster_sizes = pd.DataFrame(pd.Series(cluster_sizes).value_counts().sort_index()).reset_index()
    output_cluster_sizes.columns = ['cluster_size', 'count']

    # 2. Individual reproduction number extraction
    individual_r = []
    for person in all_infected:
        individual_r.append(G.out_degree(person) if person in G else 0)

    output_individual_r = pd.DataFrame(pd.Series(individual_r).value_counts().sort_index()).reset_index()
    output_individual_r.columns = ['individual_R', 'count']

    # 3. Extract temporal and age-stratified statistics
    output_infection = func_cal_infection(sim, df)
    output_daily_infection = output_infection[0]
    output_pair_transmission = output_infection[1]

    # 4. Extract Attack Rates
    output_attack_rate = calculate_attack_rate(sim, df)

    # 5. Extract transmission proportions across contact layers
    layer_counts = df['layer'].value_counts()
    layer_proportions = layer_counts / layer_counts.sum()

    output_layer_trans = pd.DataFrame({
        'layer': layer_counts.index,
        'transmissions': layer_counts.values,
        'proportion': layer_proportions.values
    })

    # 6. Extract Generation Intervals
    output_generation_intervals = sim.compute_gen_time().copy()
    output_generation_intervals = pd.DataFrame(output_generation_intervals, index=[0])

    # 7. Extract Doubling Time
    output_doubling_time = sim.compute_doubling()
    output_doubling_time = pd.DataFrame({"doubling": output_doubling_time})

    # 8. Extract Effective Reproduction Numbers (Rt)
    r_eff_daily = sim.compute_r_eff(method='daily').copy()
    r_eff_infectious = sim.compute_r_eff(method='infectious').copy()
    r_eff_outcome = sim.compute_r_eff(method='outcome').copy()
    output_r_eff = pd.DataFrame({'r_eff_daily': r_eff_daily,
                                 'r_eff_infectious': r_eff_infectious,
                                 'r_eff_outcome': r_eff_outcome})


    # Export compiled datasets to Excel
    with pd.ExcelWriter(f'{output_path}/save_sim/output_sim{n}.xlsx') as writer:
        output_daily_infection.to_excel(writer, sheet_name='daily_infection', index=False)
        output_attack_rate.to_excel(writer, sheet_name='attack_rate', index=False)
        output_pair_transmission.to_excel(writer, sheet_name='pair_transmission')
        output_layer_trans.to_excel(writer, sheet_name='layer_trans', index=False)
        output_cluster_sizes.to_excel(writer, sheet_name='cluster_sizes', index=False)
        output_generation_intervals.to_excel(writer, sheet_name='generation_intervals', index=False)
        output_doubling_time.to_excel(writer, sheet_name='doubling_time', index=False)
        output_individual_r.to_excel(writer, sheet_name='individual_r', index=False)
        output_r_eff.to_excel(writer, sheet_name='r_eff', index=False)



if __name__ == "__main__":
    # Scoped initialization for standalone execution
    path = "D:/ABM trans/"
    os.chdir(path)


